kind: pipeline
name: default

steps:
- name: test
  image: r-base
  commands:
  - R -e 'install.packages(c("devtools"))' -e 'devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE)'
  - R CMD build .
