kind: pipeline
name: default

steps:
- name: test
  image: r-base
  commands:
  - R -e 'install.packages(c("data.table", "knitr", "covr", "testthat", "rmarkdown", "dplyr", "tibble"))'
  - R CMD build .
