kind: pipeline
name: default

steps:
- name: test
  image: rocker/tidyverse
  commands:
  - R -e 'install.packages(c("data.table", "knitr", "covr", "testthat", "rmarkdown", "dplyr", "tibble", "rcmdcheck"))' -e 'rcmdcheck::rcmdcheck()'
  - R CMD build .
