kind: pipeline
name: default

steps:
- name: test
  image: r-base
  commands:
  - R -e 'install.packages(c("devtools"));if (!all(c("devtools") %in% installed.packages())) { q(status = 1, save = "no")}'
  - R CMD build .
