kind: pipeline
name: default

steps:
- name: test
  image: rocker/tidyverse
  commands:
  - R -e 'install.packages(c("data.table", "knitr", "covr", "testthat", "rmarkdown", "dplyr", "tibble", "rcmdcheck"))'
  - R CMD build .
  - R CMD check treeco_0.0.1.9000.tar.gz
