kind: pipeline
name: default

steps:
- name: test
  image: r-base
  commands:
  - R -e 'system("sudo apt-get install libcurl4-openssl-dev")' -e 'install.packages(c("devtools", "git2r", "httr", "usethis"))' -e 'devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE)'
  - R CMD build .
