# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_trimws <- function(x, which = "both") {
    .Call(`_treeco_cpp_trimws`, x, which)
}

timesTwo <- function(x) {
    .Call(`_treeco_timesTwo`, x)
}

